-- MapData.lua
-- Datos de cada mapa seleccionable

local MapData = {
    {
        id           = "city_night",
        name         = "Ciudad Nocturna",
        icon         = "🌆",
        description  = "Callejones oscuros con lámparas de neón. Muchos escondites.",
        minPlayers   = 2,
        timeOfDay    = 0.2,   -- noche
        fogColor     = Color3.fromRGB(20,20,40),
        fogEnd       = 200,
        ambientColor = Color3.fromRGB(30,30,60),
        musicId      = "rbxassetid://0",
        hidingSpots  = 25,
        difficulty   = "Fácil",
        unlockLevel  = 0,
    },
    {
        id           = "sewer",
        name         = "Las Alcantarillas",
        icon         = "🐀",
        description  = "Túneles húmedos y oscuros. El Ratón se mueve más rápido aquí.",
        minPlayers   = 3,
        timeOfDay    = 0.0,
        fogColor     = Color3.fromRGB(10,30,10),
        fogEnd       = 120,
        ambientColor = Color3.fromRGB(20,40,20),
        musicId      = "rbxassetid://0",
        hidingSpots  = 18,
        difficulty   = "Medio",
        unlockLevel  = 5,
        specialRule  = "MouseSpeed+3",
    },
    {
        id           = "haunted",
        name         = "Casa Embrujada",
        icon         = "👻",
        description  = "Una mansión con muchos cuartos. Las luces parpadean.",
        minPlayers   = 2,
        timeOfDay    = 0.1,
        fogColor     = Color3.fromRGB(40,0,40),
        fogEnd       = 150,
        ambientColor = Color3.fromRGB(40,0,50),
        musicId      = "rbxassetid://0",
        hidingSpots  = 30,
        difficulty   = "Difícil",
        unlockLevel  = 10,
        specialRule  = "LightsFlicker",
    },
    {
        id           = "rooftops",
        name         = "Azoteas",
        icon         = "🏙️",
        description  = "Salta entre edificios. Cuidado con caer.",
        minPlayers   = 4,
        timeOfDay    = 0.3,
        fogColor     = Color3.fromRGB(20,30,50),
        fogEnd       = 300,
        ambientColor = Color3.fromRGB(30,40,60),
        musicId      = "rbxassetid://0",
        hidingSpots  = 15,
        difficulty   = "Extremo",
        unlockLevel  = 15,
        specialRule  = "NoBoundary",
    },
    {
        id           = "forest",
        name         = "Bosque Oscuro",
        icon         = "🌲",
        description  = "Árboles gigantes y niebla densa. El radar no funciona aquí.",
        minPlayers   = 2,
        timeOfDay    = 0.15,
        fogColor     = Color3.fromRGB(10,20,10),
        fogEnd       = 80,
        ambientColor = Color3.fromRGB(15,25,15),
        musicId      = "rbxassetid://0",
        hidingSpots  = 35,
        difficulty   = "Medio",
        unlockLevel  = 8,
        specialRule  = "NoRadar",
    },
    {
        id           = "lab",
        name         = "Laboratorio",
        icon         = "🔬",
        description  = "Pasillos blancos y puertas automáticas que se abren y cierran.",
        minPlayers   = 3,
        timeOfDay    = 0.5,
        fogColor     = Color3.fromRGB(200,230,255),
        fogEnd       = 400,
        ambientColor = Color3.fromRGB(180,210,240),
        musicId      = "rbxassetid://0",
        hidingSpots  = 20,
        difficulty   = "Difícil",
        unlockLevel  = 12,
        specialRule  = "AutoDoors",
    },
}
return MapData
